---
accumulo_version: 1.6.2
accumulo_package: accumulo-{{ accumulo_version }}-bin.tar.gz
accumulo_install_dir: "{{ company_install_prefix }}/accumulo-{{ accumulo_version }}"
accumulo_home: "{{ company_install_prefix }}/accumulo"
accumulo_conf_dir: "{{ accumulo_home }}/conf"
accumulo_data_prefix: "{{ company_data_prefix }}/accumulo"
accumulo_log_dir: "{{ accumulo_data_prefix }}/logs"
