#! /usr/bin/env bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Starts Accumulo services
#
# chkconfig: 345 99 20
# description: Accumulo

. /etc/rc.d/init.d/functions

ACCUMULO_HOME={{ accumulo_home }}

RETVAL=0
case "$1" in
   start)
      sudo -u hdfs $ACCUMULO_HOME/bin/start-here.sh
      RETVAL=$?
   ;;
   stop)
      COUNT=$(pgrep -f "$ACCUMULO_HOME.*org.apache.accumulo.start" | wc -l)
      if [ $COUNT -ne 0 ]; then
         sudo -u hdfs $ACCUMULO_HOME/bin/stop-here.sh
         RETVAL=$?
      fi
   ;;
   status)
      COUNT=$(pgrep -f "$ACCUMULO_HOME.*org.apache.accumulo.start" | wc -l)
      echo "There are $COUNT accumulo processes on this machine"
   ;;
   restart)
      $0 stop
      $0 start
   ;;
   *)
      echo "Usage: $0 {start|stop|status|restart}"
      exit 1
   ;;
esac

exit 0
