---
- name: Copy run script
  template:
    src: run.sh
    dest: "{{ zookeeper_home }}/run.sh"
    mode: 0755
  tags:
    - image

- name: Create data directory
  file:
    path: "{{ zookeeper_data_dir }}"
    state: directory
    mode: 0755
  tags:
    - run

- name: Copy configuration file
  template:
    src: zoo.cfg
    dest: "{{ zookeeper_conf_dir }}/zoo.cfg"
  tags:
    - run

- name: Initialize server
  command: >
      {{ zookeeper_home }}/bin/zkServer.sh init --myid={{ ansible_env.ZOOKEEPER_SERVER_ID }}
      creates={{ zookeeper_data_dir }}/myid
  tags:
    - run
