---
ProcessEventTopology:
  parallelism:
    eventSpout: 1
    DeserializeEvent: 1
    ProcessEvent: 1

accumulo:
  instance: operational
  zooKeepers: zookeeper1.local.datafascia.com
  user: root
  password: secret

eventQueue:
  kafkaBrokers: "kafka1.local.datafascia.com:9092"
  topic: event

hl7MessageQueue:
  kafkaBrokers: "kafka1.local.datafascia.com:9092"
  topic: hl7Message
