---
ProcessEventTopology:
  parallelism:
    eventSpout: 1
    DeserializeEvent: 1
    ProcessEvent: 1

accumulo:
  instance: operational
  zooKeepers: devbox
  user: root
  password: secret

eventQueue:
  kafkaBrokers: "devbox:9092"
  topic: event

hl7MessageQueue:
  kafkaBrokers: "devbox:9092"
  topic: hl7Message
