---
accumulo:
  instance: operational
  zooKeepers: zookeeper1.local.datafascia.com
  user: root
  password: secret

df-api:
  endpoint: http://api1.local.datafascia.com:9090/fhir
  username: testuser
  password: supersecret

UcsfMedAdminProcessor:
  accumuloTable: testTable
  rxnormDb: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  rxnormDbTable: RXNCONSO
  rxnormDbUsername: testuser
  rxnormDbPassword: testpassword

UpdateHarmEvidence:
  pointOfCare: M9I,13I
