---
- name: Add {{ inventory_hostname }} to /etc/hosts file
  lineinfile:
      dest=/etc/hosts
      regexp="^{{ ansible_ssh_host }}"
      line="{{ ansible_ssh_host }} {{ inventory_hostname }}"

- name: Set hostname
  command: hostname {{ inventory_hostname }}

- name: Configure hostname
  lineinfile:
      dest=/etc/sysconfig/network
      regexp="^HOSTNAME="
      line="HOSTNAME={{ inventory_hostname }}"
