---
- name: Set hostname
  command: hostname {{ inventory_hostname }}

- name: Configure hostname
  lineinfile:
      dest=/etc/sysconfig/network
      regexp="^HOSTNAME="
      line="HOSTNAME={{ inventory_hostname }}"
