---
- name: Install Ansible
  yum: name=ansible

- name: Create {{ docker_image_creator_home }} directory
  file:
    path: "{{ docker_image_creator_home }}"
    state: directory
    mode: 0755

- name: Package Ansible scripts
  local_action: command tar czf /tmp/ansible.tar.gz ansible
      chdir={{ playbook_dir }}/..
  sudo: no

- name: Copy Ansible scripts
  copy:
    src: /tmp/ansible.tar.gz
    dest: "{{ company_package_dir }}/ansible.tar.gz"

- name: Extract Ansible scripts
  command: tar --no-same-owner -xzf {{ company_package_dir }}/ansible.tar.gz
      chdir={{ docker_image_creator_home }}

- name: Copy centos7-ansible-java Dockerfile
  template:
    src: centos7-ansible-java-Dockerfile
    dest: "{{ company_package_dir }}/centos7-ansible-java-Dockerfile"

- name: Create centos7-ansible-java base Docker image
  shell: >
      docker build
      --file={{ company_package_dir }}/centos7-ansible-java-Dockerfile
      --tag=datafascia/centos7-ansible-java
      {{ company_package_dir }} &&
      touch {{ docker_image_creator_home }}/centos7-ansible-java.created
      creates={{ docker_image_creator_home }}/centos7-ansible-java.created

- name: Copy ZooKeeper Dockerfile
  template:
    src: "{{ playbook_dir }}/roles/zookeeper-server/templates/zookeeper-Dockerfile"
    dest: "{{ company_package_dir }}/zookeeper-Dockerfile"

- name: Create ZooKeeper Docker image
  shell: >
      docker build
      --file={{ company_package_dir }}/zookeeper-Dockerfile
      --tag=datafascia/zookeeper
      {{ company_package_dir }} &&
      touch {{ docker_image_creator_home }}/zookeeper.created
      creates={{ docker_image_creator_home }}/zookeeper.created

- name: Copy Accumulo master primary Dockerfile
  template:
    src: "{{ playbook_dir }}/roles/accumulo-master-primary/templates/accumulo-master-primary-Dockerfile"
    dest: "{{ company_package_dir }}/accumulo-master-primary-Dockerfile"

- name: Create Accumulo master primary Docker image
  shell: >
      docker build
      --file={{ company_package_dir }}/accumulo-master-primary-Dockerfile
      --tag=datafascia/accumulo-master-primary
      {{ company_package_dir }} &&
      touch {{ docker_image_creator_home }}/accumulo-master-primary.created
      creates={{ docker_image_creator_home }}/accumulo-master-primary.created

- name: Copy Accumulo master standby Dockerfile
  template:
    src: "{{ playbook_dir }}/roles/accumulo-master-standby/templates/accumulo-master-standby-Dockerfile"
    dest: "{{ company_package_dir }}/accumulo-master-standby-Dockerfile"

- name: Create Accumulo master standby Docker image
  shell: >
      docker build
      --file={{ company_package_dir }}/accumulo-master-standby-Dockerfile
      --tag=datafascia/accumulo-master-standby
      {{ company_package_dir }} &&
      touch {{ docker_image_creator_home }}/accumulo-master-standby.created
      creates={{ docker_image_creator_home }}/accumulo-master-standby.created

- name: Copy Accumulo slave Dockerfile
  template:
    src: "{{ playbook_dir }}/roles/accumulo-slave/templates/accumulo-slave-Dockerfile"
    dest: "{{ company_package_dir }}/accumulo-slave-Dockerfile"

- name: Create Accumulo slave Docker image
  shell: >
      docker build
      --file={{ company_package_dir }}/accumulo-slave-Dockerfile
      --tag=datafascia/accumulo-slave
      {{ company_package_dir }} &&
      touch {{ docker_image_creator_home }}/accumulo-slave.created
      creates={{ docker_image_creator_home }}/accumulo-slave.created

- name: Copy Kafka Dockerfile
  template:
    src: "{{ playbook_dir }}/roles/kafka/templates/kafka-Dockerfile"
    dest: "{{ company_package_dir }}/kafka-Dockerfile"

- name: Create Kafka Docker image
  shell: >
      docker build
      --file={{ company_package_dir }}/kafka-Dockerfile
      --tag=datafascia/kafka
      {{ company_package_dir }} &&
      touch {{ docker_image_creator_home }}/kafka.created
      creates={{ docker_image_creator_home }}/kafka.created

- name: Copy Storm nimbus Dockerfile
  template:
    src: "{{ playbook_dir }}/roles/storm-nimbus/templates/storm-nimbus-Dockerfile"
    dest: "{{ company_package_dir }}/storm-nimbus-Dockerfile"

- name: Create Storm nimbus Docker image
  shell: >
      docker build
      --file={{ company_package_dir }}/storm-nimbus-Dockerfile
      --tag=datafascia/storm-nimbus
      {{ company_package_dir }} &&
      touch {{ docker_image_creator_home }}/storm-nimbus.created
      creates={{ docker_image_creator_home }}/storm-nimbus.created

- name: Copy Storm supervisor Dockerfile
  template:
    src: "{{ playbook_dir }}/roles/storm-supervisor/templates/storm-supervisor-Dockerfile"
    dest: "{{ company_package_dir }}/storm-supervisor-Dockerfile"

- name: Create Storm supervisor Docker image
  shell: >
      docker build
      --file={{ company_package_dir }}/storm-supervisor-Dockerfile
      --tag=datafascia/storm-supervisor
      {{ company_package_dir }} &&
      touch {{ docker_image_creator_home }}/storm-supervisor.created
      creates={{ docker_image_creator_home }}/storm-supervisor.created

- name: Copy application package
  copy:
    src: "{{ playbook_dir }}/../../shell/target/df-shell-{{ df_platform_version }}-bin.tar.gz"
    dest: "{{ company_package_dir }}/df-shell-{{ df_platform_version }}-bin.tar.gz"

- name: Copy df-etl-hl7-ingest Dockerfile
  template:
    src: "{{ playbook_dir }}/roles/df-etl-hl7-ingest/templates/df-etl-hl7-ingest-Dockerfile"
    dest: "{{ company_package_dir }}/df-etl-hl7-ingest-Dockerfile"

- name: Create df-etl-hl7-ingest Docker image
  shell: >
      docker build
      --file={{ company_package_dir }}/df-etl-hl7-ingest-Dockerfile
      --tag=datafascia/df-etl-hl7-ingest
      {{ company_package_dir }} &&
      touch {{ docker_image_creator_home }}/df-etl-hl7-ingest.created
      creates={{ docker_image_creator_home }}/df-etl-hl7-ingest.created
