---
- name: Install Hadoop
  yum: name=hadoop-{{ hadoop_version }}

- name: Create {{ company_data_prefix }}/hadoop directory
  file:
    path: "{{ company_data_prefix }}/hadoop"
    state: directory
    mode: 0775
    owner: root
    group: hadoop

- name: Copy configuration files
  template:
      src={{ item }}
      dest={{ hadoop_conf_dir }}/{{ item }}
      mode=664
  with_items:
    - core-site.xml
    - hdfs-site.xml
    - mapred-site.xml
    - masters
    - slaves
    - yarn-site.xml
