---
kafka_version: 0.8.2.0
kafka_package: kafka_2.10-{{ kafka_version }}.tgz
kafka_install_dir: "{{ company_install_prefix }}/kafka_2.10-{{ kafka_version }}"
kafka_home: "{{ company_install_prefix }}/kafka"
kafka_data_prefix: "{{ company_data_prefix }}/kafka"
kafka_data_dir: "{{ kafka_data_prefix }}/data"
kafka_logs_dir: "{{ kafka_data_prefix }}/logs"
