---
HL7MessageToEventTopology:
  parallelism:
    hl7MessageSpout: 1
    DeserializeMessage: 1
    SaveMessage: 1
    ParseMessage: 1
    HandleAdmitMessage: 1
    HandleObservationMessage: 1

accumulo:
  instance: operational
  zooKeepers: devbox
  user: root
  password: secret

hl7MessageQueue:
  kafkaBrokers: "devbox:9092"
  topic: hl7Message
