---
- name: Create {{ dnsmasq_hosts_dir }} directory
  file:
    path: "{{ dnsmasq_hosts_dir }}"
    state: directory

- name: Install dnsmasq
  yum: name=dnsmasq

- name: Configure dnsmasq
  lineinfile:
    dest: /etc/dnsmasq.conf
    line: addn-hosts={{ dnsmasq_hosts_dir }}

- name: Copy Docker run script
  template:
    src: docker-run.sh
    dest: "{{ docker_run_command }}"
    mode: 0755

- name: Check for changed NiFi flow configuration
  copy:
    src: "{{ playbook_dir }}/roles/df-etl/files/flow.xml.gz"
    dest: "{{ company_package_dir }}/flow.xml.gz"
  register: copy_flow_xml_gz

- name: Stop df-etl
  shell: docker stop etl1.local.datafascia.com && docker rm -v etl1.local.datafascia.com
  ignore_errors: True
  when: copy_df_etl_nar.changed or copy_flow_xml_gz.changed

- name: Stop df-api-server
  shell: docker stop api1.local.datafascia.com && docker rm -v api1.local.datafascia.com
  ignore_errors: True
  when: copy_df_api_server.changed

- name: List Docker containers
  shell: docker ps | awk '{ print $2 }'
  register: list_containers

- name: Run ZooKeeper
  command: >
      {{ docker_run_command }}
          {{ groups['zookeeper'][0] }}
          --detach
          --env=ZOOKEEPER_SERVERS={{ groups['zookeeper'] | join(',') }}
          --env=ZOOKEEPER_SERVER_ID={{ hostvars[groups['zookeeper'][0]]['zookeeper_server_id'] }}
          --publish=2181:2181
          --publish=2888:2888
          --publish=3888:3888
          --volume={{ company_data_prefix }}:{{ company_data_prefix }}
          datafascia/zookeeper
  when: "'datafascia/zookeeper:latest' not in list_containers.stdout_lines"

- name: Run Accumulo master primary container
  command: >
      {{ docker_run_command }}
          {{ groups['accumulo-master-primary'][0] }}
          --detach
          --env=ACCUMULO_MASTER_PRIMARY_HOST={{ groups['accumulo-master-primary'][0] }}
          --env=ACCUMULO_MASTER_STANDBY_HOST={{ groups['accumulo-master-standby'][0] }}
          --env=ACCUMULO_SLAVE_HOSTS={{ groups['accumulo-slave'] | join(',') }}
          --env=ZOOKEEPER_SERVERS={{ groups['zookeeper'] | join(',') }}
          --hostname={{ groups['accumulo-master-primary'][0] }}
          --publish=4560:4560
          --publish=8020:8020
          --publish=9999:9999
          --publish=50070:50070
          --publish=50095:50095
          --volume={{ company_data_prefix }}:{{ company_data_prefix }}
          datafascia/accumulo-master-primary
  when: "'datafascia/accumulo-master-primary:latest' not in list_containers.stdout_lines"

- name: Run Accumulo master standby container
  command: >
      {{ docker_run_command }}
          {{ groups['accumulo-master-standby'][0] }}
          --detach
          --env=ACCUMULO_MASTER_PRIMARY_HOST={{ groups['accumulo-master-primary'][0] }}
          --env=ACCUMULO_MASTER_STANDBY_HOST={{ groups['accumulo-master-standby'][0] }}
          --env=ACCUMULO_SLAVE_HOSTS={{ groups['accumulo-slave'] | join(',') }}
          --env=ZOOKEEPER_SERVERS={{ groups['zookeeper'] | join(',') }}
          --hostname={{ groups['accumulo-master-standby'][0] }}
          --publish=12234:12234
          --publish=50090:50090
          --publish=50091:50091
          --volume={{ company_data_prefix }}:{{ company_data_prefix }}
          datafascia/accumulo-master-standby
  when: "'datafascia/accumulo-master-standby:latest' not in list_containers.stdout_lines"

- name: Run Accumulo slave container
  command: >
      {{ docker_run_command }}
          {{ groups['accumulo-slave'][0] }}
          --detach
          --env=ACCUMULO_MASTER_PRIMARY_HOST={{ groups['accumulo-master-primary'][0] }}
          --env=ACCUMULO_MASTER_STANDBY_HOST={{ groups['accumulo-master-standby'][0] }}
          --env=ACCUMULO_SLAVE_HOSTS={{ groups['accumulo-slave'] | join(',') }}
          --env=ZOOKEEPER_SERVERS={{ groups['zookeeper'] | join(',') }}
          --hostname={{ groups['accumulo-slave'][0] }}
          --publish=9997:9997
          --publish=50010:50010
          --publish=50020:50020
          --publish=50075:50075
          --volume={{ company_data_prefix }}:{{ company_data_prefix }}
          datafascia/accumulo-slave
  when: "'datafascia/accumulo-slave:latest' not in list_containers.stdout_lines"

- name: Wait for HDFS namenode to start
  command: >
      docker exec {{ groups['accumulo-master-primary'][0] }}
      ansible localhost
      --connection=local
      --module-name=wait_for
      --args="host={{ groups['accumulo-master-primary'][0] }} port=8020 timeout=30"
  when: "'datafascia/accumulo-master-primary:latest' not in list_containers.stdout_lines"

- name: Wait for HDFS to become available
  command: >
      docker exec {{ groups['accumulo-master-primary'][0] }}
      su hdfs -c "hdfs dfsadmin -safemode wait"
  when: "'datafascia/accumulo-master-primary:latest' not in list_containers.stdout_lines"

- name: Initialize Accumulo instance
  shell: >
      docker exec {{ groups['accumulo-master-primary'][0] }}
      su hdfs -c "{{ accumulo_home }}/bin/accumulo init --clear-instance-name --instance-name {{ accumulo_instance }} --password {{ accumulo_password }}" &&
      touch {{ accumulo_data_prefix }}/instance.initialized
      creates={{ accumulo_data_prefix }}/instance.initialized

- name: Start Accumulo master primary
  command: >
      docker exec {{ groups['accumulo-master-primary'][0] }}
      su hdfs -c "{{ accumulo_home }}/bin/start-here.sh"

- name: Start Accumulo master standby
  command: >
      docker exec {{ groups['accumulo-master-standby'][0] }}
      su hdfs -c "{{ accumulo_home }}/bin/start-here.sh"

- name: Start Accumulo slave
  command: >
      docker exec {{ groups['accumulo-slave'][0] }}
      su hdfs -c "{{ accumulo_home }}/bin/start-here.sh"

- name: Run Kafka
  command: >
      {{ docker_run_command }}
          {{ groups['kafka'][0] }}
          --detach
          --env=KAFKA_ADVERTISED_HOST={{ groups['kafka'][0] }}
          --env=KAFKA_BROKER_ID={{ hostvars[groups['kafka'][0]]['kafka_broker_id'] }}
          --env=ZOOKEEPER_SERVERS={{ groups['zookeeper'] | join(',') }}
          --publish=9092:9092
          --volume={{ company_data_prefix }}:{{ company_data_prefix }}
          datafascia/kafka
  when: "'datafascia/kafka:latest' not in list_containers.stdout_lines"

- name: Create {{ company_data_prefix }}/nifi/conf directory
  file:
    path: "{{ company_data_prefix }}/nifi/conf"
    state: directory

- name: Copy NiFi flow configuration
  copy:
    src: "{{ playbook_dir }}/roles/df-etl/files/flow.xml.gz"
    dest: "{{ company_data_prefix }}/nifi/conf/flow.xml.gz"

- name: Run df-etl
  command: >
      {{ docker_run_command }}
          etl1.local.datafascia.com
          --detach
          --publish=8080:8080
          --publish=9520:9520
          --volume={{ company_data_prefix }}:{{ company_data_prefix }}
          datafascia/df-etl
  when: "'datafascia/df-etl:latest' not in list_containers.stdout_lines"

- name: Run df-api-server
  command: >
      {{ docker_run_command }}
          api1.local.datafascia.com
          --detach
          --env=ZOOKEEPER_SERVERS={{ groups['zookeeper'] | join(',') }}
          --publish=8081:8081
          --publish=9090:9090
          --volume={{ company_data_prefix }}:{{ company_data_prefix }}
          datafascia/df-api-server
  when: "'datafascia/df-api-server:latest' not in list_containers.stdout_lines"
