---
storm.local.dir: {{ storm_local_dir }}

storm.log.dir: {{ storm_log_dir }}

storm.zookeeper.servers:
{% for host in ansible_env.ZOOKEEPER_SERVERS.split(',') %}
  - {{ host }}
{% endfor %}

nimbus.host: {{ ansible_env.STORM_NIMBUS_HOST }}

nimbus.childopts: "-Xmx1g {{ storm_java_opts }} -Xloggc:{{ storm_log_dir }}/gc-nimbus.log"

ui.childopts: "-Xmx768m {{ storm_java_opts }} -Xloggc:{{ storm_log_dir }}/gc-ui.log"

supervisor.childopts: "-Xmx256m {{ storm_java_opts }} -Xloggc:{{ storm_log_dir }}/gc-supervisor.log"

worker.childopts: "-Xmx1g -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 {{ storm_java_opts }} -Xloggc:{{ storm_log_dir }}/gc-worker.log"

supervisor.slots.ports:
  - 6700
  - 6701
