---
- name: Install HDFS namenode
  yum: name=hadoop-hdfs-namenode-{{ hadoop_version }}
  tags:
    - image

- name: Format HDFS namenode
  command: su hdfs -c "hdfs namenode -format"
      creates={{ hdfs_dfs_name_dir[0] }}
  tags:
    - run

- name: Start HDFS namenode
  service:
    name: hadoop-hdfs-namenode
    state: started
  tags:
    - run
