Vagrant.configure('2') do |config|
  config.vm.box = 'puppetlabs/centos-7.0-64-nocm'
  config.vm.network 'private_network', ip: '192.168.222.222'

  config.vm.provider 'virtualbox' do |virtualbox|
    virtualbox.name = 'dataFasciaDockerHost'
    virtualbox.customize ['modifyvm', :id, '--memory', '6144']
  end

  config.vm.provision 'ansible' do |ansible|
    ansible.extra_vars = { environment_name: 'local' }
    ansible.inventory_path = 'ansible/environment/local/hosts'
    ansible.playbook = 'ansible/local.yml'
    ansible.skip_tags = ['image', 'run']
  end
end
