Vagrant.configure('2') do |config|
  config.vm.box = 'puppetlabs/centos-6.5-64-nocm'
  config.vm.box_url = 'https://vagrantcloud.com/puppetlabs/boxes/centos-6.5-64-nocm'
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.network :forwarded_port, guest: 50070, host: 50070
  config.vm.network :forwarded_port, guest: 50095, host: 50095

  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.name = 'dataFascia'
    virtualbox.customize ['modifyvm', :id, '--memory', '6144']
  end

  config.vm.provision :ansible do |ansible|
    ansible.extra_vars = { environment_name: 'local' }
    ansible.host_key_checking = false
    ansible.inventory_path = 'ansible/environment/local/hosts'
    ansible.playbook = 'ansible/local.yml'
  end
end
