---
- name: Download Kafka package
  get_url:
      url=http://mirrors.ibiblio.org/apache/kafka/{{ kafka_version }}/{{ kafka_package }}
      dest={{ company_package_dir }}/{{ kafka_package }}

- name: Extract Kafka
  command: tar xzf {{ company_package_dir }}/{{ kafka_package }}
      chdir={{ company_install_prefix }}
      creates={{ kafka_install_dir }}

- name: Create symbolic link {{ kafka_home }} to install directory
  file:
      src={{ kafka_install_dir }}
      path={{ kafka_home }}
      state=link

- name: Create directories
  file:
      path={{ item }}
      state=directory
      mode=755
  with_items:
    - "{{ kafka_data_dir }}"
    - "{{ kafka_logs_dir }}"

- name: Copy configuration files
  template:
      src={{ item }}
      dest={{ kafka_home }}/config/{{ item }}
      mode=755
  with_items:
    - log4j.properties
    - server.properties

- name: Copy Upstart configuration file
  template:
      src=kafka.conf
      dest=/etc/init/kafka.conf

- name: Start Kafka
  command: /sbin/initctl start kafka
  ignore_errors: True
