// Copyright (C) 2015-2016 dataFascia Corporation - All Rights Reserved
// For license information, please contact http://datafascia.com/contact
package com.datafascia.rules.examples.simple;

import com.datafascia.rules.model.RxNorm;

global org.slf4j.Logger log;
 
dialect "mvel"

rule "Intermittent Chloradiazepoxide Enteral"
    when
        $p:RxNorm(rxcuiSCD == "905516")
    then
        $p.setGroupName("Intermittent Chloradiazepoxide Enteral");
	      log.info("\t==> Executing RULE 'Intermittent Chloradiazepoxide Enteral' for Object: " + $p);
end
