---
- name: Download Elasticsearch package
  get_url:
      url=https://download.elasticsearch.org/elasticsearch/elasticsearch/{{ elasticsearch_package }}
      dest={{ company_package_dir }}/{{ elasticsearch_package }}

- name: Install Elasticsearch
  command: rpm --install {{ company_package_dir }}/{{ elasticsearch_package }}
      creates=/etc/elasticsearch

- name: Create work directories
  file:
      path={{ item }}
      owner=elasticsearch
      group=elasticsearch
      state=directory
  with_items:
    - "{{ elasticsearch_data_prefix }}/logs"
    - "{{ elasticsearch_data_prefix }}/work"

- name: Create data directory
  file:
      path={{ item }}
      owner=elasticsearch
      group=elasticsearch
      state=directory
  with_items: elasticsearch_data_dir

- name: Copy Elasticsearch init configuration file
  template:
      src=elasticsearch
      dest=/etc/sysconfig/elasticsearch

- name: Copy Elasticsearch configuration file
  template:
      src=elasticsearch.yml
      dest=/etc/elasticsearch/elasticsearch.yml

- name: Start Elasticsearch
  service:
      name=elasticsearch
      state=started
      enabled=yes
