// Copyright (C) 2015-2016 dataFascia Corporation - All Rights Reserved
// For license information, please contact http://datafascia.com/contact
package com.datafascia.rules;

import com.datafascia.rules.model.RxNorm;
import com.datafascia.rules.rxnorm.FrequencyLookup;
import com.datafascia.rules.rxnorm.RouteLookup;

global org.slf4j.Logger log;
 
dialect "mvel"

/** 
 *  These rules take a RxNorm model as input ($p) and read the fields
 *  route, freuqency, pca, brand, rxcuiSCD, ahfs, drugID and rxcuiIN.
 *  Based on their content, if an event matches a rule the rule will write fields
 *  medsSetCode and medsSetName.
 *  
 *  Rule A26 "Intermittent Oxycodone-acetaminophen Enteral"
 *  	We need to be provided a brand name.
 *
 *  Rule A26 "Intermittent Hydrocodone-acetaminophen Enteral" and
 *  Rule A24 "Intermittent Oxycodone (IR) Enteral" will both fire for:
 *  RxNorm (RXCUI for TTY = IN) = 7804
 *  Brand name = Anything but OxyContin 
 *  Rule A50 "Intermittent Lorazepam Enteral" needs to be provided a frequency.
 */

rule "Intermittent Cisatracurium IV"
  when
    $p:RxNorm(rxcuiIn == "319864" && FrequencyLookup.isIntermittent(frequency))
  then
    $p.setMedsSetCode("UCSF_A2");
    $p.setMedsSetName("Intermittent Cisatracurium IV");
end

rule "Intermittent Vecuronium IV"
  when
    $p:RxNorm(rxcuiIn == "71535" && FrequencyLookup.isIntermittent(frequency))
  then
    $p.setMedsSetCode("UCSF_A3");
    $p.setMedsSetName("Intermittent Vecuronium IV");
end

rule "Intermittent Rocuronium IV"
  when
    $p:RxNorm(rxcuiIn == "68139" && FrequencyLookup.isIntermittent(frequency))
  then
    $p.setMedsSetCode("UCSF_A4");
    $p.setMedsSetName("Intermittent Rocuronium IV");
end

rule "Intermittent Pancuronium IV"
  when
    $p:RxNorm(rxcuiIn == "7883" && FrequencyLookup.isIntermittent(frequency))
  then
    $p.setMedsSetCode("UCSF_A5");
    $p.setMedsSetName("Intermittent Pancuronium IV");
end

rule "Continuous Infusion Cisatracurium IV"
  when
    $p:RxNorm(rxcuiIn == "319864" && FrequencyLookup.isContinuous(frequency))
  then
    $p.setMedsSetCode("UCSF_A6");
    $p.setMedsSetName("Continuous Infusion Cisatracurium IV");
end

rule "Continuous Infusion Vecuronium IV"
  when
    $p:RxNorm(rxcuiIn == "71535" && FrequencyLookup.isContinuous(frequency))
  then
    $p.setMedsSetCode("UCSF_A7");
    $p.setMedsSetName("Continuous Infusion Vecuronium IV");
end

rule "Epidural"
  when
    $p:RxNorm((rxcuiIn == "1815" ||
               rxcuiIn ==  "35780" ||
               rxcuiIn ==  "4337" ||
               rxcuiIn ==  "3423" ||
               rxcuiIn ==   "7052")
               && FrequencyLookup.isContinuous(frequency) &&  route == "50")   
  then
    $p.setMedsSetCode("UCSF_A8");
    $p.setMedsSetName("Epidural");
end

rule "Peripheral Nerve Infusion"
  when
    $p:RxNorm((rxcuiIn == "1815" ||
                rxcuiIn == "35780" ||
                rxcuiIn == "4337" ||
                rxcuiIn == "3423" ||
                rxcuiIn == "7052")
                && FrequencyLookup.isContinuous(frequency) && route == "157")
  then
    $p.setMedsSetCode("UCSF_A9");
    $p.setMedsSetName("Peripheral Nerve Infusion");
end

rule "Fentanyl PCA"
  when
    $p:RxNorm(rxcuiIn == "4337" && FrequencyLookup.isContinuous(frequency) &&
              RouteLookup.isIV(route) && pca == "yes")
  then
    $p.setMedsSetCode("UCSF_A10");
    $p.setMedsSetName("Fentanyl PCA");
end

rule "Hydromorphone PCA"
  when
    $p:RxNorm(rxcuiIn == "3423" && FrequencyLookup.isContinuous(frequency) &&
              RouteLookup.isIV(route) && pca == "yes")
  then
    $p.setMedsSetCode("UCSF_A11");
    $p.setMedsSetName("Hydromorphone PCA");
end

rule "Morphine PCA"
  when
    $p:RxNorm(rxcuiIn == "7052" && FrequencyLookup.isContinuous(frequency) &&
              RouteLookup.isIV(route) && pca == "yes")
  then
    $p.setMedsSetCode("UCSF_A12");
    $p.setMedsSetName("Morphine PCA");
end

rule "Intermittent Fentanyl IV"
  when
    $p:RxNorm(rxcuiIn == "4337" && FrequencyLookup.isIntermittent(frequency) &&
              (RouteLookup.isIV(route) || route == "6"))
  then
    $p.setMedsSetCode("UCSF_A13");
    $p.setMedsSetName("Intermittent Fentanyl IV");
end

rule "Continuous Infusion Fentanyl IV"
  when
    $p:RxNorm(rxcuiIn == "4337" && FrequencyLookup.isContinuous(frequency) &&
              RouteLookup.isIV(route) && pca == "no")
  then
    $p.setMedsSetCode("UCSF_A14");
    $p.setMedsSetName("Continuous Infusion Fentanyl IV");
end

rule "Fentanyl Transdermal"
  when
    $p:RxNorm(rxcuiIn == "4337" && route == "20")
  then
    $p.setMedsSetCode("UCSF_A15");
    $p.setMedsSetName("Fentanyl Transdermal");
end

rule "Intermittent Hydromorphone IV"
  when
    $p:RxNorm(rxcuiIn == "3423" && FrequencyLookup.isIntermittent(frequency)
              && RouteLookup.isIV(route))
  then
    $p.setMedsSetCode("UCSF_A16");
    $p.setMedsSetName("Intermittent Hydromorphone IV");
end

rule "Continuous Infusion Hydromorphone IV"
  when
    $p:RxNorm(rxcuiIn == "3423" && FrequencyLookup.isContinuous(frequency) &&
              RouteLookup.isIV(route) && pca == "no")
  then
    $p.setMedsSetCode("UCSF_A17");
    $p.setMedsSetName("Continuous Infusion Hydromorphone IV");
end

rule "Intermittent Hydromorphone Enteral"
  when
    $p:RxNorm(rxcuiIn == "3423" && RouteLookup.isNonRectalEnteral(route))
  then
    $p.setMedsSetCode("UCSF_A18");
    $p.setMedsSetName("Intermittent Hydromorphone Enteral");
end

rule "Continuous Infusion Remifentanil IV"
  when
    $p:RxNorm(rxcuiIn == "73032" && FrequencyLookup.isContinuous(frequency)
              && RouteLookup.isIV(route) && pca == "no")
  then
    $p.setMedsSetCode("UCSF_A19");
    $p.setMedsSetName("Continuous Infusion Remifentanil IV");
end

rule "Intermittent Morphine IV"
  when
    $p:RxNorm(rxcuiIn == "7052" && FrequencyLookup.isIntermittent(frequency)
              && (RouteLookup.isIV(route) || route == "6"))
  then
    $p.setMedsSetCode("UCSF_A20");
    $p.setMedsSetName("Intermittent Morphine IV");
end

rule "Continuous Infusion Morphine IV"
  when
    $p:RxNorm(rxcuiIn == "7052" && FrequencyLookup.isContinuous(frequency)
              && RouteLookup.isIV(route)
              && pca == "no")
  then
    $p.setMedsSetCode("UCSF_A21");
    $p.setMedsSetName("Continuous Infusion Morphine IV");
end

rule "Intermittent Morphine (IR) Enteral"
  when
    $p:RxNorm(rxcuiIn == "7052" &&
              brand != "MS Contin" && brand != "Kadian" && brand != "Avinza" &&
              RouteLookup.isNonRectalEnteral(route))
  then
    $p.setMedsSetCode("UCSF_A22");
    $p.setMedsSetName("Intermittent Morphine (IR) Enteral");
end

rule "Intermittent Morphine (SR) Enteral"
  when
    $p:RxNorm(rxcuiIn == "7052" && route == "15" &&
               (brand == "MS Contin" || brand == "Kadian" || brand == "Avinza"))
  then
    $p.setMedsSetCode("UCSF_A23");
    $p.setMedsSetName("Intermittent Morphine (SR) Enteral");
end

rule "Intermittent Oxycodone (IR) Enteral"
  when
    $p:RxNorm(rxcuiIn == "7804" && rxcuiIn != "161" && brand != "OxyContin")
  then
    $p.setMedsSetCode("UCSF_A24");
    $p.setMedsSetName("Intermittent Oxycodone (IR) Enteral"); 
end

rule "Intermittent Oxycodone (SR) Enteral"
  when
    $p:RxNorm(rxcuiIn == "7804" && brand == "OxyContin")
  then
    $p.setMedsSetCode("UCSF_A25");
    $p.setMedsSetName("Intermittent Oxycodone (SR) Enteral");
end

rule "Intermittent Oxycodone-acetaminophen Enteral"
  when
    // Problem! Brand name in "ID Clues sheet": "n/a"! I am guessing the brand is Percocet!
    $p:RxNorm((rxcuiIn == "7804" || rxcuiIn == "161") && brand == "Percocet")
  then
    $p.setMedsSetCode("UCSF_A26");
    $p.setMedsSetName("Intermittent Oxycodone-acetaminophen Enteral");
end

rule "Intermittent Hydrocodone-acetaminophen Enteral"
  when
    $p:RxNorm(rxcuiIn == "5489" || rxcuiIn =="161")
  then
    $p.setMedsSetCode("UCSF_A27");
    $p.setMedsSetName("Intermittent Hydrocodone-acetaminophen Enteral");
end

rule "Intermittent Methadone IV"
  when
    $p:RxNorm(rxcuiIn == "6813" && RouteLookup.isIV(route))
  then
    $p.setMedsSetCode("UCSF_A28");
    $p.setMedsSetName("Intermittent Methadone IV");
end

rule "Intermittent Methadone Enteral"
  when
    $p:RxNorm(rxcuiIn == "6813" && RouteLookup.isNonRectalEnteral(route))
  then
    $p.setMedsSetCode("UCSF_A29");
    $p.setMedsSetName("Intermittent Methadone Enteral");
end

rule "Intermittent Tramadol Enteral"
  when
    $p:RxNorm(rxcuiSCD == "836408" ||
              rxcuiSCD == "835603" ||
              rxcuiSCD == "849566")
  then
    $p.setMedsSetCode("UCSF_A30");
    $p.setMedsSetName("Intermittent Tramadol Enteral");
end

rule "Intermittent Ibuprofen Enteral"
  when
    $p:RxNorm(rxcuiSCD == "310963" ||
              rxcuiSCD == "198405" ||
              rxcuiSCD == "197803" ||
              rxcuiSCD == "310964" ||
              rxcuiSCD == "310965" ||
              rxcuiSCD == "197805" ||
              rxcuiSCD == "314047" ||
              rxcuiSCD == "204442" ||
              rxcuiSCD == "197806" ||
              rxcuiSCD == "197807")
  then
    $p.setMedsSetCode("UCSF_A31");
    $p.setMedsSetName("Intermittent Ibuprofen Enteral");
end

rule "Intermittent Celecoxib Enteral"
  when
    $p:RxNorm(rxcuiIn == "140587")
  then
    $p.setMedsSetCode("UCSF_A32");
    $p.setMedsSetName("Intermittent Celecoxib Enteral");
end

rule "Intermittent Ketorolac IV"
  when
    $p:RxNorm(rxcuiIn == "35827" && (RouteLookup.isIV(route) || route == "6"))
  then
    $p.setMedsSetCode("UCSF_A33");
    $p.setMedsSetName("Intermittent Ketorolac IV");
end

rule "Intermittent Acetaminophen with Codeine Enteral"
  when
    $p:RxNorm(rxcuiSCD == "993755" ||
              rxcuiSCD == "993763" ||
              rxcuiSCD == "993770" || 
              rxcuiSCD == "993781" || 
              rxcuiSCD == "993890" ||
              rxcuiSCD == "996968" || 
              rxcuiSCD == "996969" || 
              rxcuiSCD == "993932" || 
              rxcuiSCD == "996973" || 
              rxcuiSCD == "996974" || 
              rxcuiSCD == "994043" ||
              rxcuiSCD == "994046" || 
              rxcuiSCD == "994049" ||  
              rxcuiSCD == "996981" || 
              rxcuiSCD == "996982" || 
              rxcuiSCD == "994059" || 
              rxcuiSCD == "996983")
  then
    $p.setMedsSetCode("UCSF_A34");
    $p.setMedsSetName("Intermittent Acetaminophen with Codeine Enteral");
end

rule "Intermittent Acetaminophen Enteral"
  when
    $p:RxNorm(rxcuiSCD == "1148399" ||
              rxcuiSCD == "238159" ||
              rxcuiSCD == "243675" ||
              rxcuiSCD == "243677" ||
              rxcuiSCD == "313820" ||
              rxcuiSCD == "477282" ||
              rxcuiSCD == "307675" ||
              rxcuiSCD == "307668" ||
              rxcuiSCD == "603136" ||
              rxcuiSCD == "198436" ||
              rxcuiSCD == "313782" ||
              rxcuiSCD == "307684" ||
              rxcuiSCD == "665056" ||
              rxcuiSCD == "603139" ||
              rxcuiSCD == "1536880" ||
              rxcuiSCD == "198439" ||
              rxcuiSCD == "198440" ||
              rxcuiSCD == "247974" ||
              rxcuiSCD == "198444" ||
              rxcuiSCD == "307696" ||
              rxcuiSCD == "251374" ||
              rxcuiSCD == "307695" ||
              rxcuiSCD == "247661")
  then
    $p.setMedsSetCode("UCSF_A35");
    $p.setMedsSetName("Intermittent Acetaminophen Enteral"); 
end

rule "Intermittent Acetaminophen IV"
  when
    $p:RxNorm(rxcuiIn == "161" && RouteLookup.isIV(route))
  then
    $p.setMedsSetCode("UCSF_A36");
    $p.setMedsSetName("Intermittent Acetaminophen IV");
end

rule "Intermittent Acetaminophen PR"
  when
    $p:RxNorm(rxcuiIn == "161" && route == "17")
  then
    $p.setMedsSetCode("UCSF_A37");
    $p.setMedsSetName("Intermittent Acetaminophen PR");
end

rule "Intermittent Gabapentin Enteral"
  when
    $p:RxNorm(rxcuiIn == "25480" && RouteLookup.isNonRectalEnteral(route))
  then
    $p.setMedsSetCode("UCSF_A38");
    $p.setMedsSetName("Intermittent Gabapentin Enteral");
end

rule "Intermittent Pregabalin Enteral"
  when
    $p:RxNorm(rxcuiIn == "187832")
  then
    $p.setMedsSetCode("UCSF_A39");
    $p.setMedsSetName("Intermittent Pregabalin Enteral");
end

rule "Intermittent Ketamine Enteral"
  when
    $p:RxNorm(rxcuiIn == "6130" && RouteLookup.isNonRectalEnteral(route))
  then
    $p.setMedsSetCode("UCSF_A40");
    $p.setMedsSetName("Intermittent Ketamine Enteral");
end

rule "Continuous Infusion Ketamine IV"
  when
    $p:RxNorm(rxcuiIn == "6130" && FrequencyLookup.isContinuous(frequency) &&
              RouteLookup.isIV(route) && pca == "no")
  then
    $p.setMedsSetCode("UCSF_A41");
    $p.setMedsSetName("Continuous Infusion Ketamine IV");
end

rule "Intermittent Ketamine IV"
  when
    $p:RxNorm(rxcuiIn == "6130" && FrequencyLookup.isIntermittent(frequency) &&
              (RouteLookup.isIV(route) || route == "6"))
  then
    $p.setMedsSetCode("UCSF_A42");
    $p.setMedsSetName("Intermittent Ketamine IV");
end

rule "Lidocaine 5% Transdermal"
  when
    $p:RxNorm(rxcuiSCD == "1009464")
  then
    $p.setMedsSetCode("UCSF_A43");
    $p.setMedsSetName("Lidocaine 5% Transdermal");
end

rule "Intermittent Morphine Intrathecal"
  when
    $p:RxNorm(FrequencyLookup.isIntermittent(frequency) && 
              (rxcuiSCD == "892477" || rxcuiSCD =="892365"))
  then
    $p.setMedsSetCode("UCSF_A44");
    $p.setMedsSetName("Intermittent Morphine Intrathecal");
end

rule "Continuous Infusion Intrathecal"
  when
    $p:RxNorm(FrequencyLookup.isContinuous(frequency) && route == "9")
  then
    $p.setMedsSetCode("UCSF_A45");
    $p.setMedsSetName("Continuous Infusion Intrathecal");
end

rule "Headache Analgesics (Miscellaneous) Enteral"
  when
    $p:RxNorm(rxcuiSCD == "756245" ||
              rxcuiSCD == "889520" ||
              rxcuiSCD == "238153" ||
              rxcuiSCD == "238154" ||
              rxcuiSCD == "308322" ||
              rxcuiSCD == "240093" ||
              rxcuiSCD == "476152" ||
              rxcuiSCD == "647869" ||
              rxcuiSCD == "205251" ||
              rxcuiSCD == "243694" ||
              rxcuiSCD == "827318" ||
              rxcuiSCD == "308297" ||
              rxcuiSCD == "763116" ||
              rxcuiSCD == "692836")
  then
    $p.setMedsSetCode("UCSF_A46");
    $p.setMedsSetName("Headache Analgesics (Miscellaneous) Enteral");
end

rule "Continuous Infusion Propofol IV"
  when
    $p:RxNorm(rxcuiIn == "8782" && FrequencyLookup.isContinuous(frequency))
  then
    $p.setMedsSetCode("UCSF_A47");
    $p.setMedsSetName("Continuous Infusion Propofol IV");
end

rule "Continuous Infusion Dexmedetomidine IV"
  when
    $p:RxNorm(rxcuiIn == "48937" && FrequencyLookup.isContinuous(frequency))
  then
    $p.setMedsSetCode("UCSF_A48");
    $p.setMedsSetName("Continuous Infusion Dexmedetomidine IV");
end

rule "Intermittent Lorazepam IV"
  when
    $p:RxNorm(rxcuiIn == "6470" && FrequencyLookup.isIntermittent(frequency) &&
               (RouteLookup.isIV(route) || route == "6"))
  then
    $p.setMedsSetCode("UCSF_A49");
    $p.setMedsSetName("Intermittent Lorazepam IV");
end

rule "Intermittent Lorazepam Enteral"
  when
    $p:RxNorm(rxcuiIn == "6470" && frequency == "n/a" && RouteLookup.isNonRectalEnteral(route))
  then
    $p.setMedsSetCode("UCSF_A50");
    $p.setMedsSetName("Intermittent Lorazepam Enteral");
end

rule "Continuous Infusion Lorazepam IV"
  when
    $p:RxNorm(rxcuiIn == "6470" && FrequencyLookup.isContinuous(frequency) &&
              RouteLookup.isIV(route))
  then
    $p.setMedsSetCode("UCSF_A51");
    $p.setMedsSetName("Continuous Infusion Lorazepam IV");
end

rule "Intermittent Midazolam IV"
  when
    $p:RxNorm(rxcuiIn == "6960" && FrequencyLookup.isIntermittent(frequency) &&
               (RouteLookup.isIV(route) || route == "6"))
  then
    $p.setMedsSetCode("UCSF_A52");
    $p.setMedsSetName("Intermittent Midazolam IV");
end

rule "Continuous Infusion Midazolam IV"
  when
    $p:RxNorm(rxcuiIn == "6960" && FrequencyLookup.isContinuous(frequency) &&
              RouteLookup.isIV(route))
  then
    $p.setMedsSetCode("UCSF_A53");
    $p.setMedsSetName("Continuous Infusion Midazolam IV");
end

rule "Intermittent Clonazepam Enteral"
  when
    $p:RxNorm(rxcuiIn == "2598")
  then
    $p.setMedsSetCode("UCSF_A54");
    $p.setMedsSetName("Intermittent Clonazepam Enteral");
end

rule "Intermittent Diazepam IV"
  when
    $p:RxNorm(rxcuiIn == "3322" && (RouteLookup.isIV(route) || route == "6"))
  then
    $p.setMedsSetCode("UCSF_A55");
    $p.setMedsSetName("Intermittent Diazepam IV");
end

rule "Intermittent Diazepam Enteral"
  when
    $p:RxNorm(rxcuiIn == "3322" && (RouteLookup.isNonRectalEnteral(route) || route == "17"))
  then
    $p.setMedsSetCode("UCSF_A56");
    $p.setMedsSetName("Intermittent Diazepam Enteral");
end

rule "Intermittent Chloradiazepoxide Enteral"
  when
    $p:RxNorm(rxcuiSCD == "905369" ||
              rxcuiSCD == "905532" ||
              rxcuiSCD == "905495" || 
              rxcuiSCD == "905505" ||
              rxcuiSCD == "905516")
  then
    $p.setMedsSetCode("UCSF_A57");
    $p.setMedsSetName("Intermittent Chloradiazepoxide Enteral");
end

rule "Intermittent Alprazalom Enteral"
  when
    $p:RxNorm(rxcuiIn == "596")
  then
    $p.setMedsSetCode("UCSF_A58");
    $p.setMedsSetName("Intermittent Alprazalom Enteral");
end

rule "Intermittent Warfarin Enteral"
  when
    $p:RxNorm(rxcuiIn == "11289")
  then
    $p.setMedsSetCode("UCSF_A59");
    $p.setMedsSetName("Intermittent Warfarin Enteral");
end

rule "Continuous Infusion Argatroban IV"
  when
    $p:RxNorm(rxcuiIn == "15202" && FrequencyLookup.isContinuous(frequency))
  then
    $p.setMedsSetCode("UCSF_A60");
    $p.setMedsSetName("Continuous Infusion Argatroban IV");
end

rule "Continuous Infusion Bivalirudin IV"
  when
    $p:RxNorm(rxcuiIn == "60819" && FrequencyLookup.isContinuous(frequency))
  then
    $p.setMedsSetCode("UCSF_A61");
    $p.setMedsSetName("Continuous Infusion Bivalirudin IV");
end

rule "Intermittent Dabigatran Enteral"
  when
    $p:RxNorm(rxcuiIn == "1546356")
  then
    $p.setMedsSetCode("UCSF_A62");
    $p.setMedsSetName("Intermittent Dabigatran Enteral");
end

rule "Intermittent Apixaban Enteral"
  when
    $p:RxNorm(rxcuiIn == "1364430")
  then
    $p.setMedsSetCode("UCSF_A63");
    $p.setMedsSetName("Intermittent Apixaban Enteral");
end

rule "Intermittent Rivaroxaban Enteral"
  when
    $p:RxNorm(rxcuiIn == "1114195")
  then
    $p.setMedsSetCode("UCSF_A64");
    $p.setMedsSetName("Intermittent Rivaroxaban Enteral");
end

rule "Intermittent Edoxaban Enteral"
  when
    $p:RxNorm(rxcuiIn == "1599538")
  then
    $p.setMedsSetCode("UCSF_A65");
    $p.setMedsSetName("Intermittent Edoxaban Enteral");
end

rule "Intermittent Fondaparinux SC"
  when
    $p:RxNorm(rxcuiIn == "321208")
  then
    $p.setMedsSetCode("UCSF_A66");
    $p.setMedsSetName("Intermittent Fondaparinux SC");
end

rule "Intermittent Enoxaparin"
  when
    $p:RxNorm(rxcuiIn == "67108" && (frequency == "q12h" || frequency =="q24h"))
  then
    $p.setMedsSetCode("UCSF_A67");
    $p.setMedsSetName("Intermittent Enoxaparin");
end

rule "Continuous Infusion Heparin IV"
  when
    $p:RxNorm(drugId == "206328" ||
              drugId == "15846")
  then
    $p.setMedsSetCode("UCSF_A68");
    $p.setMedsSetName("Continuous Infusion Heparin IV");
end

rule "Intermittent Heparin SC"
  when
    $p:RxNorm(rxcuiIn == "235473" && route == "subcutaneous")
  then
    $p.setMedsSetCode("UCSF_A69");
    $p.setMedsSetName("Intermittent Heparin SC");
end

rule "Stress Ulcer Prophylactics"
  when
    $p:RxNorm(ahfs == "56:28.12" ||
              ahfs == "56:28.36" ||
              ahfs == "56:28.12" ||
              ahfs == "56:28.36")
  then
    $p.setMedsSetCode("UCSF_A70");
    $p.setMedsSetName("Stress Ulcer Prophylactics");
end

rule "Continuous Infusion Dopamine IV"
  when
    $p:RxNorm(rxcuiIn == "3628" && FrequencyLookup.isContinuous(frequency))
  then
    $p.setMedsSetCode("UCSF_A71");
    $p.setMedsSetName("Continuous Infusion Dopamine IV");
end

rule "Continuous Infusion Epinephrine IV"
  when
    $p:RxNorm(rxcuiIn == "3992" && FrequencyLookup.isContinuous(frequency) &&
              RouteLookup.isIV(route))
  then
    $p.setMedsSetCode("UCSF_A72");
    $p.setMedsSetName("Continuous Infusion Epinephrine IV");
end

rule "Continuous Infusion Norepinephrine IV"
  when
    $p:RxNorm(rxcuiIn == "7512" && FrequencyLookup.isContinuous(frequency))
  then
    $p.setMedsSetCode("UCSF_A73");
    $p.setMedsSetName("Continuous Infusion Norepinephrine IV");
end

rule "Continuous Infusion Phenylephrine IV"
  when
    $p:RxNorm(rxcuiIn == "8163" && FrequencyLookup.isContinuous(frequency) &&
              RouteLookup.isIV(route))
  then
    $p.setMedsSetCode("UCSF_A74");
    $p.setMedsSetName("Continuous Infusion Phenylephrine IV");
end

rule "Continuous Infusion Vasopressin IV"
  when
    $p:RxNorm(rxcuiIn == "11149" && FrequencyLookup.isContinuous(frequency))
  then
    $p.setMedsSetCode("UCSF_A75");
    $p.setMedsSetName("Continuous Infusion Vasopressin IV");
end

rule "Continuous Infusion Dobutamine IV"
  when
    $p:RxNorm(rxcuiIn == "3616" && FrequencyLookup.isContinuous(frequency))
  then
    $p.setMedsSetCode("UCSF_A76");
    $p.setMedsSetName("Continuous Infusion Dobutamine IV");
end

rule "Continuous Infusion Milrinone IV"
  when
    $p:RxNorm(rxcuiIn == "52769" && FrequencyLookup.isContinuous(frequency))
  then
    $p.setMedsSetCode("UCSF_A77");
    $p.setMedsSetName("Continuous Infusion Milrinone IV");
end

rule "Continuous Infusion Isoproterenol IV"
  when
    $p:RxNorm(rxcuiIn == "6054" && FrequencyLookup.isContinuous(frequency) &&
              RouteLookup.isIV(route))
  then
    $p.setMedsSetCode("UCSF_A78");
    $p.setMedsSetName("Continuous Infusion Isoproterenol IV");
end

rule "Chemotherapy IV"
  when
    $p:RxNorm(ahfs == "10:00.00" && RouteLookup.isIV(route))
  then
    $p.setMedsSetCode("UCSF_A79");
    $p.setMedsSetName("Chemotherapy IV");
end

rule "Total Parenteral Nutrition (TPN)"
  when
    $p:RxNorm(drugId == "40801561")
  then
    $p.setMedsSetCode("UCSF_A80");
    $p.setMedsSetName("Total Parenteral Nutrition (TPN)");
end

rule "Continuous Infusion Epoprostenol  IV"
  when
    $p:RxNorm(rxcuiIn == "8814" && FrequencyLookup.isContinuous(frequency))
  then
    $p.setMedsSetCode("UCSF_A81");
    $p.setMedsSetName("Continuous Infusion Epoprostenol  IV");
end

rule "Continuous Infusion Treprostinil IV"
  when
    $p:RxNorm(rxcuiIn == "343048" && FrequencyLookup.isContinuous(frequency) &&
              RouteLookup.isIV(route))
  then
    $p.setMedsSetCode("UCSF_A82");
    $p.setMedsSetName("Continuous Infusion Treprostinil IV");
end

rule "Intermittent Non-Enteric Coated Pancrelipase Enteral"
  when
    $p:RxNorm(RouteLookup.isNonJejunalEnteral(route) &&
               (rxcuiSCD == "1247386" || rxcuiSCD == "1247379"))
  then
    $p.setMedsSetCode("UCSF_A83");
    $p.setMedsSetName("Intermittent Non-Enteric Coated Pancrelipase Enteral");
end

rule "Intermittent Clopidogrel Enteral"
  when
    $p:RxNorm(rxcuiIn == "32968")
  then
    $p.setMedsSetCode("UCSF_A84");
    $p.setMedsSetName("Intermittent Clopidogrel Enteral");
end

rule "Intermittent Prasugrel Enteral"
  when
    $p:RxNorm(rxcuiIn == "613391")
  then
    $p.setMedsSetCode("UCSF_A85");
    $p.setMedsSetName("Intermittent Prasugrel Enteral");
end

rule "Intermittent Ticagrelor Enteral"
  when
    $p:RxNorm(rxcuiIn == "1116632")
  then
    $p.setMedsSetCode("UCSF_A86");
    $p.setMedsSetName("Intermittent Ticagrelor Enteral");
end

rule "Intermittent Aspirin Enteral"
  when
    $p:RxNorm(rxcuiIn == "1191" && 
               (RouteLookup.isNonRectalEnteral(route) || route == "17"))
  then
    $p.setMedsSetCode("UCSF_A87");
    $p.setMedsSetName("Intermittent Aspirin Enteral");
end

rule "Hydrocortisone"
  when
    $p:RxNorm((RouteLookup.isNonRectalEnteral(route) || RouteLookup.isIV(route) || route == "6") &&
              (rxcuiSCD == "238755" ||
               rxcuiSCD == "197782" ||
               rxcuiSCD == "310899" ||
               rxcuiSCD == "310900" ||
               rxcuiSCD == "238754" ||
               rxcuiSCD == "197783" ||
               rxcuiSCD == "199320" || 
               rxcuiSCD == "197787"))
  then
    $p.setMedsSetCode("UCSF_A88");
    $p.setMedsSetName("Hydrocortisone");
end

rule "Intermittent Prednisone Enteral"
  when
    $p:RxNorm(rxcuiIn == "8640")
  then
    $p.setMedsSetCode("UCSF_A89");
    $p.setMedsSetName("Intermittent Prednisone Enteral");
end

rule "Intermittent Methylprednisolone"
  when
    $p:RxNorm(rxcuiIn == "6902" && 
              (RouteLookup.isNonRectalEnteral(route) || RouteLookup.isIV(route)  || route == "6"))
  then
    $p.setMedsSetCode("UCSF_A90");
    $p.setMedsSetName("Intermittent Methylprednisolone");
end

rule "Intermittent Dexamethasone"
  when
    $p:RxNorm(rxcuiIn == "3264" &&
               (RouteLookup.isNonRectalEnteral(route) || RouteLookup.isIV(route)))
  then
    $p.setMedsSetCode("UCSF_A91");
    $p.setMedsSetName("Intermittent Dexamethasone");
end

rule "Intermittent Cortisone Enteral"
  when
    $p:RxNorm(rxcuiIn == "2878")
  then
    $p.setMedsSetCode("UCSF_A92");
    $p.setMedsSetName("Intermittent Cortisone Enteral");
end

rule "Intermittent Prednisolone Enteral"
  when
    $p:RxNorm(rxcuiIn == "8638" && RouteLookup.isNonRectalEnteral(route))
  then
    $p.setMedsSetCode("UCSF_A93");
    $p.setMedsSetName("Intermittent Prednisolone Enteral");
end
