---
- name: Install HDFS datanode
  yum: name=hadoop-hdfs-datanode-{{ hadoop_version }}

- name: Create data directory
  file:
      path={{ item }}
      state=directory
      owner=hdfs
      group=hadoop
      mode=775
  with_items: hdfs_dfs_data_dir

- name: Start HDFS datanode
  service:
      name=hadoop-hdfs-datanode
      state=started
      enabled=yes
