---
- name: Install HDFS datanode
  yum: name=hadoop-hdfs-datanode-{{ hadoop_version }}
  tags:
    - image

- name: Create data directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: hdfs
    group: hadoop
  with_items: hdfs_dfs_data_dir
  tags:
    - run

- name: Start HDFS datanode
  service:
    name: hadoop-hdfs-datanode
    state: started
  tags:
    - run
