---
- name: Stop firewall
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Install device-mapper
  yum: name=device-mapper-{{ device_mapper_version }}

- name: Install Docker
  yum: name=docker-{{ docker_version }}

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
