---
- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
  ignore_errors: True

- name: Set vm.swappiness to Accumulo recommended value
  sysctl:
    name: vm.swappiness
    value: 0
  ignore_errors: True

- name: Stop firewall
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_distribution == 'CentOS'

- name: Install LVM2
  yum: name=lvm2-{{ lvm2_version }}
  when: ansible_distribution == 'CentOS'

- name: Install Docker
  yum: name=docker-{{ docker_version }}

- name: Copy Docker configuration
  copy:
    src: docker
    dest: /etc/sysconfig/docker

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
