---
- name: Download Storm archive
  get_url:
      url=http://mirrors.ibiblio.org/apache/storm/apache-storm-{{ storm_version }}/{{ storm_package }}
      dest={{ company_package_dir }}/{{ storm_package }}

- name: Extract Storm archive
  command: tar xzf {{ company_package_dir }}/{{ storm_package }}
      chdir={{ company_install_prefix }}
      creates={{ company_install_prefix }}/apache-storm-{{ storm_version }}

- name: Create symbolic link to Storm install
  file:
      src={{ company_install_prefix }}/apache-storm-{{ storm_version }}
      path={{ storm_home }}
      state=link

- name: Create local working directory
  file:
      path={{ storm_local_dir }}
      state=directory
      mode=755

- name: Copy Storm configuration file
  template:
      src=storm.yaml
      dest={{ storm_home }}/conf/storm.yaml
      mode=644

- name: Download Jackson JAR files
  get_artifact:
      repository_url=http://central.maven.org/maven2
      groupId=com.fasterxml.jackson.core
      artifactId={{ item }}
      version={{ jackson_version }}
      packaging=jar
      dest={{ storm_home }}/lib/{{ item }}-{{ jackson_version }}.jar
  with_items:
    - jackson-annotations
    - jackson-core
    - jackson-databind

- name: Download logback-gelf JAR file
  get_artifact:
      repository_url=http://central.maven.org/maven2
      groupId=com.github.pukkaone
      artifactId=logback-gelf
      version={{ logback_gelf_version }}
      packaging=jar
      dest={{ storm_home }}/lib/logback-gelf-{{ logback_gelf_version }}.jar

- name: Copy logback configuration file
  template:
      src=cluster.xml
      dest={{ storm_home }}/logback/cluster.xml
      mode=644
