---
- name: Install Nginx
  yum: name=nginx

- name: Start Nginx
  service:
      name=nginx
      state=started
      enabled=yes

- name: Download Kibana package
  get_url:
      url=https://download.elasticsearch.org/kibana/kibana/{{ kibana_package }}
      dest={{ company_package_dir }}/{{ kibana_package }}

- name: Extract Kibana
  command: tar xzf {{ company_package_dir }}/{{ kibana_package }}
      chdir={{ nginx_document_root_dir }}
      creates={{ kibana_install_dir }}

- name: Create symbolic link to Kibana install
  file:
      src={{ kibana_install_dir }}
      path={{ nginx_document_root_dir }}/kibana
      state=link

- name: Copy Kibana configuration file
  template:
      src=config.js
      dest={{ kibana_install_dir }}/config.js
