---
- name: Download Java Development Kit
  uri:
      url=http://download.oracle.com/otn-pub/java/jdk/{{ jdk_package_version }}-{{ jdk_package_build }}/{{ jdk_package }}
      HEADER_Cookie=oraclelicense=accept-securebackup-cookie
      dest={{ company_prefix }}/{{ jdk_package }}
      creates={{ company_prefix }}/{{ jdk_package }}

- name: Install Java Development Kit
  command: rpm --install {{ company_prefix }}/{{ jdk_package }}
      creates=/usr/java/jdk{{ jdk_version }}

- name: Install Unlimited Strength Jurisdiction Policy Files
  copy:
      src={{ item }}
      dest=/usr/java/jdk{{ jdk_version }}/jre/lib/security/{{ item }}
  with_items:
    - local_policy.jar
    - US_export_policy.jar

- name: Set system default Java version
  command: /usr/sbin/alternatives --install /usr/bin/java java /usr/java/latest/bin/java 20000
