---
- name: Download Java
  get_url:
    url: http://s3-us-west-2.amazonaws.com/datafascia-packages/{{ java_package }}
    dest: "{{ company_package_dir }}/{{ java_package }}"

- name: Install Java
  command: >
      rpm --install {{ company_package_dir }}/{{ java_package }}
      creates=/usr/java/jre{{ java_version }}

- name: Install Unlimited Strength Jurisdiction Policy Files
  copy:
    src: "{{ item }}"
    dest: /usr/java/jre{{ java_version }}/lib/security/{{ item }}
  with_items:
    - local_policy.jar
    - US_export_policy.jar

- name: Set system default Java version
  command: /usr/sbin/alternatives --install /usr/bin/java java /usr/java/latest/bin/java 20000
