---
- name: Download Java
  uri:
      url=http://download.oracle.com/otn-pub/java/jdk/{{ java_package_version }}-{{ java_package_build }}/{{ java_package }}
      HEADER_Cookie=oraclelicense=accept-securebackup-cookie
      dest={{ company_prefix }}/{{ java_package }}
      creates={{ company_prefix }}/{{ java_package }}

- name: Install Java
  command: rpm --install {{ company_prefix }}/{{ java_package }}
      creates=/usr/java/jre{{ java_version }}

- name: Install Unlimited Strength Jurisdiction Policy Files
  copy:
      src={{ item }}
      dest=/usr/java/jre{{ java_version }}/lib/security/{{ item }}
  with_items:
    - local_policy.jar
    - US_export_policy.jar

- name: Set system default Java version
  command: /usr/sbin/alternatives --install /usr/bin/java java /usr/java/latest/bin/java 20000
