---
- name: Create {{ company_package_dir }} directory
  file:
    path: "{{ company_package_dir }}"
    state: directory
    mode: 0755

- name: Read {{ ephemeral_dir }} status
  stat: path={{ ephemeral_dir }}
  register: ephemeral_stat

- name: Create {{ company_data_prefix }} directory
  file:
    path: "{{ company_data_prefix }}"
    state: directory
    mode: 0755
  when: ephemeral_stat.stat.exists == False

- name: Create symbolic link {{ company_data_prefix }} to {{ ephemeral_dir }}
  file:
    src: "{{ ephemeral_dir }}"
    path: "{{ company_data_prefix }}"
    state: link
  when: ephemeral_stat.stat.exists == True
