---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - environment/{{ environment_name }}/vars.yml
  roles:
    - { role: common, tags: [ image ] }
    - hadoop-hdfs-namenode
    - accumulo-master-primary
