---
- hosts: default
  sudo: yes
  vars:
    local_home: "{{ lookup('env', 'HOME') }}"
  vars_files:
    - environment/{{ environment_name }}/vars.yml
  roles:
    - zookeeper-server
    - storm-nimbus
    - storm-supervisor
    - hadoop-hdfs-namenode
    - hadoop-hdfs-datanode
    - accumulo-master-primary
    - accumulo-slave
    - kafka
