---
- name: Download Accumulo package
  get_url:
      url=https://s3-us-west-2.amazonaws.com/datafascia-packages/{{ accumulo_package }}
      dest={{ company_package_dir }}/{{ accumulo_package }}
  tags:
    - image

- name: Extract Accumulo
  command: tar --no-same-owner -xzf {{ company_package_dir }}/{{ accumulo_package }}
      chdir={{ company_install_prefix }}
      creates={{ accumulo_install_dir }}
  tags:
    - image

- name: Create symbolic link {{ accumulo_home }} to install directory
  file:
      src={{ accumulo_install_dir }}
      path={{ accumulo_home }}
      state=link
  tags:
    - image

- name: Create {{ accumulo_home }}/lib/native directory
  file:
      path={{ accumulo_home }}/lib/native
      state=directory
      mode=755
  tags:
    - image

- name: Copy native library
  copy:
      src=libaccumulo.so
      dest={{ accumulo_home }}/lib/native/libaccumulo.so
      mode=755
  tags:
    - image

- name: Create directories
  file:
      path={{ item }}
      state=directory
      mode=775
      owner=hdfs
      group=hadoop
  with_items:
    - "{{ accumulo_conf_dir }}"
    - "{{ accumulo_log_dir }}"
  tags:
    - run

- name: Copy configuration files
  template:
      src={{ item }}
      dest={{ accumulo_conf_dir }}/{{ item }}
      mode=664
      owner=root
      group=hadoop
  with_items:
    - accumulo-env.sh
    - accumulo-metrics.xml
    - accumulo-site.xml
    - gc
    - generic_logger.xml
    - log4j.properties
    - masters
    - monitor_logger.xml
    - slaves
    - tracers
  tags:
    - run
